<?php
/**
 * Demo products — BILOHASH ecosystem CMS scripts (digital licenses).
 */
return [
    [
        'id' => 'shop-cms-license',
        'category' => 'laptops-computers',
        'featured' => true,
        'active' => true,
        'price' => 2490,
        'sale_price' => 1990,
        'sku' => 'BH-SHOP-001',
        'stock' => 999,
        'name' => [
            'en' => 'Shop CMS — PHP e-commerce script',
            'no' => 'Shop CMS — PHP nettbutikk',
            'uk' => 'Shop CMS — PHP інтернет-крамниця',
            'ru' => 'Shop CMS — PHP интернет-магазин',
        ],
        'desc' => [
            'en' => 'Product catalog, cart, Stripe/PayPal/Vipps, admin panel, Schema.org SEO. 1 domain per license.',
            'no' => 'Produktkatalog, handlekurv, Stripe/PayPal/Vipps, admin, Schema.org SEO. 1 domene per lisens.',
            'uk' => 'Каталог, кошик, Stripe/PayPal/Vipps, адмінка, Schema.org SEO. 1 домен на ліцензію.',
            'ru' => 'Каталог, корзина, Stripe/PayPal/Vipps, админка, Schema.org SEO. 1 домен на лицензию.',
        ],
        'image' => 'https://bilohash.com/shop/site/assets/img/og-shop.png',
    ],
    [
        'id' => 'booking-cms-license',
        'category' => 'smartphones-tv-electronics',
        'featured' => true,
        'active' => true,
        'price' => 2490,
        'sale_price' => 0,
        'sku' => 'BH-BOOK-001',
        'stock' => 999,
        'name' => [
            'en' => 'Booking CMS — appointments & calendar',
            'no' => 'Booking CMS — avtaler og kalender',
            'uk' => 'Booking CMS — записи та календар',
            'ru' => 'Booking CMS — записи и календарь',
        ],
        'desc' => [
            'en' => 'Services, staff schedules, online booking. Part of BILOHASH ecosystem — monthly: 1 script, yearly: all releases.',
            'no' => 'Tjenester, timeplan, online booking. Del av BILOHASH-økosystemet.',
            'uk' => 'Послуги, розклад, онлайн-запис. Частина екосистеми BILOHASH.',
            'ru' => 'Услуги, расписание, онлайн-запись. Часть экосистемы BILOHASH.',
        ],
        'image' => 'https://images.unsplash.com/photo-1506784365847-bbad939e9335?w=800&q=80',
    ],
    [
        'id' => 'faktura-cms-license',
        'category' => 'appliances',
        'featured' => true,
        'active' => true,
        'price' => 1990,
        'sale_price' => 1490,
        'sku' => 'BH-FAKT-001',
        'stock' => 999,
        'name' => [
            'en' => 'Faktura CMS — invoicing & clients',
            'no' => 'Faktura CMS — fakturering og kunder',
            'uk' => 'Faktura CMS — рахунки та клієнти',
            'ru' => 'Faktura CMS — счета и клиенты',
        ],
        'desc' => [
            'en' => 'Invoices, PDF export, client portal. Subscribe to one script or full CMS library on one domain.',
            'no' => 'Fakturaer, PDF, kundeportal. Ett skript eller hele CMS-biblioteket på ett domene.',
            'uk' => 'Рахунки, PDF, портал клієнта. Один скрипт або вся бібліотека CMS на одному домені.',
            'ru' => 'Счета, PDF, портал клиента. Один скрипт или вся библиотека CMS на одном домене.',
        ],
        'image' => 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80',
    ],
    [
        'id' => 'gamehub-cms-license',
        'category' => 'gaming',
        'featured' => false,
        'active' => true,
        'price' => 2490,
        'sale_price' => 0,
        'sku' => 'BH-GAME-001',
        'stock' => 999,
        'name' => [
            'en' => 'GameHub CMS — game catalog & news',
            'no' => 'GameHub CMS — spillkatalog og nyheter',
            'uk' => 'GameHub CMS — каталог ігор і новини',
            'ru' => 'GameHub CMS — каталог игр и новости',
        ],
        'desc' => [
            'en' => 'Game listings, reviews, affiliate-ready layout. Updates included with yearly all-scripts plan.',
            'no' => 'Spillister, anmeldelser, affiliate-klar layout. Oppdateringer med årlig fullplan.',
            'uk' => 'Списки ігор, огляди. Оновлення входять до річного плану «усі скрипти».',
            'ru' => 'Списки игр, обзоры. Обновления в годовом плане «все скрипты».',
        ],
        'image' => 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&q=80',
    ],
    [
        'id' => 'ecosystem-full-yearly',
        'category' => 'home-goods',
        'featured' => true,
        'active' => true,
        'price' => 24900,
        'sale_price' => 19900,
        'sku' => 'BH-ECO-FULL',
        'stock' => 99,
        'name' => [
            'en' => 'All CMS scripts — yearly (1 domain)',
            'no' => 'Alle CMS-skript — årlig (1 domene)',
            'uk' => 'Усі CMS-скрипти — річна ліцензія (1 домен)',
            'ru' => 'Все CMS-скрипты — годовая лицензия (1 домен)',
        ],
        'desc' => [
            'en' => 'Full BILOHASH library: all releases, security patches and feature updates for one domain per year.',
            'no' => 'Hele BILOHASH-biblioteket: alle utgivelser og oppdateringer for ett domene per år.',
            'uk' => 'Повна бібліотека BILOHASH: усі релізи та оновлення на 1 домен на рік.',
            'ru' => 'Полная библиотека BILOHASH: все релизы и обновления на 1 домен в год.',
        ],
        'image' => 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80',
    ],
    [
        'id' => 'wordpress-ai-bundle',
        'category' => 'fashion-shoes-jewelry',
        'featured' => false,
        'active' => true,
        'price' => 990,
        'sale_price' => 0,
        'sku' => 'BH-WP-AI',
        'stock' => 999,
        'name' => [
            'en' => 'WordPress AI chat plugin + theme kit',
            'no' => 'WordPress AI-chat plugin + tema',
            'uk' => 'WordPress AI-чат плагін + тема',
            'ru' => 'WordPress AI-чат плагин + тема',
        ],
        'desc' => [
            'en' => 'bilohash-ai-chat-consultant plugin, Grok/GPT ready. Monthly plan: choose one CMS or WP stack on one domain.',
            'no' => 'AI-chat plugin, Grok/GPT. Månedlig plan: ett CMS på ett domene.',
            'uk' => 'AI-чат плагін, Grok/GPT. Місячний план: один CMS на одному домені.',
            'ru' => 'AI-чат плагин, Grok/GPT. Месячный план: один CMS на одном домене.',
        ],
        'image' => 'https://images.unsplash.com/photo-1611162617474-5b21e039e986?w=800&q=80',
    ],
];