<?php
/**
 * Demo shop products — Norway / Europe + BILOHASH ecosystem CMS licenses.
 */
$products = [
    [
        'id' => 'wireless-headphones-pro',
        'category' => 'smartphones-tv-electronics',
        'featured' => true,
        'active' => true,
        'price' => 2490,
        'sale_price' => 1990,
        'sku' => 'SH-ELEC-001',
        'stock' => 24,
        'name' => [
            'en' => 'Wireless noise-cancelling headphones Pro',
            'no' => 'Trådløse støydempende hodetelefoner Pro',
            'uk' => 'Бездротові навушники з шумозаглушенням Pro',
            'ru' => 'Беспроводные наушники с шумоподавлением Pro',
        ],
        'desc' => [
            'en' => '40h battery, Bluetooth 5.3, foldable design. Demo listing for electronics storefront.',
            'no' => '40 timers batteri, Bluetooth 5.3, sammenleggbar. Demoprodukt for elektronikk.',
            'uk' => '40 годин батареї, Bluetooth 5.3, складана конструкція. Демо для електроніки.',
            'ru' => '40 часов батареи, Bluetooth 5.3, складная конструкция. Демо для электроники.',
        ],
        'image' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
    ],
    [
        'id' => 'smartwatch-fitness',
        'category' => 'smartphones-tv-electronics',
        'featured' => true,
        'active' => true,
        'price' => 1890,
        'sale_price' => 0,
        'sku' => 'SH-ELEC-002',
        'stock' => 18,
        'name' => [
            'en' => 'Smartwatch Fitness S — GPS & heart rate',
            'no' => 'Smartklokke Fitness S — GPS og puls',
            'uk' => 'Смартгодинник Fitness S — GPS і пульс',
            'ru' => 'Смарт-часы Fitness S — GPS и пульс',
        ],
        'desc' => [
            'en' => 'AMOLED display, 5 ATM water resistance, sleep tracking. Ships from Oslo warehouse (demo).',
            'no' => 'AMOLED-skjerm, 5 ATM vanntett, søvnssporing. Sendes fra Oslo-lager (demo).',
            'uk' => 'AMOLED-екран, 5 ATM, відстеження сну. Відправка зі складу в Осло (демо).',
            'ru' => 'AMOLED-экран, 5 ATM, отслеживание сна. Отправка со склада в Осло (демо).',
        ],
        'image' => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80',
    ],
    [
        'id' => 'merino-wool-sweater',
        'category' => 'fashion-shoes-jewelry',
        'featured' => true,
        'active' => true,
        'price' => 1290,
        'sale_price' => 990,
        'sku' => 'SH-FASH-001',
        'stock' => 32,
        'name' => [
            'en' => 'Merino wool crew-neck sweater — Nordic grey',
            'no' => 'Merinoull genser rund hals — nordisk grå',
            'uk' => 'Светр з мериносової вовни — nordic grey',
            'ru' => 'Свитер из мериносовой шерсти — nordic grey',
        ],
        'desc' => [
            'en' => 'Soft 100% merino, sizes XS–XL. Sustainable fashion demo for Norwegian boutiques.',
            'no' => 'Myk 100 % merino, størrelser XS–XL. Bærekraftig motedemo for norske butikker.',
            'uk' => 'М\'яка 100% меринос, розміри XS–XL. Демо стійкої моди для Норвегії.',
            'ru' => 'Мягкий 100% меринос, размеры XS–XL. Демо устойчивой моды для Норвегии.',
        ],
        'image' => 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800&q=80',
    ],
    [
        'id' => 'leather-crossbody-bag',
        'category' => 'fashion-shoes-jewelry',
        'featured' => false,
        'active' => true,
        'price' => 2190,
        'sale_price' => 0,
        'sku' => 'SH-FASH-002',
        'stock' => 14,
        'name' => [
            'en' => 'Vegetable-tanned leather crossbody bag',
            'no' => 'Crossbody-veske i vegetabilsk garvet lær',
            'uk' => 'Сумка crossbody з рослинного шкіри',
            'ru' => 'Сумка crossbody из растительной кожи',
        ],
        'desc' => [
            'en' => 'Handcrafted in EU, adjustable strap, interior zip pocket. Fashion catalog demo.',
            'no' => 'Håndlaget i EU, justerbar stropp, glidelåslomme. Mote-katalogdemo.',
            'uk' => 'Ручна робота в ЄС, регульований ремінь, внутрішня кишеня. Демо каталогу моди.',
            'ru' => 'Ручная работа в ЕС, регулируемый ремень, внутренний карман. Демо каталога моды.',
        ],
        'image' => 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80',
    ],
    [
        'id' => 'scandinavian-table-lamp',
        'category' => 'home-goods',
        'featured' => true,
        'active' => true,
        'price' => 890,
        'sale_price' => 0,
        'sku' => 'SH-HOME-001',
        'stock' => 40,
        'name' => [
            'en' => 'Scandinavian oak table lamp — warm LED',
            'no' => 'Skandinavisk eik bordlampe — varm LED',
            'uk' => 'Скандинавська настільна лампа з дуба — теплий LED',
            'ru' => 'Скандинавская настольная лампа из дуба — тёплый LED',
        ],
        'desc' => [
            'en' => 'Minimal design, dimmable 2700K bulb included. Home & interior shop demo.',
            'no' => 'Minimalistisk design, dimbar 2700K-pære inkludert. Demo for interiørbutikk.',
            'uk' => 'Мінімалістичний дизайн, димована лампа 2700K. Демо для інтер\'єру.',
            'ru' => 'Минималистичный дизайн, диммируемая лампа 2700K. Демо для интерьера.',
        ],
        'image' => 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80',
    ],
    [
        'id' => 'ceramic-dinner-set',
        'category' => 'home-goods',
        'featured' => false,
        'active' => true,
        'price' => 1590,
        'sale_price' => 1290,
        'sku' => 'SH-HOME-002',
        'stock' => 22,
        'name' => [
            'en' => 'Ceramic dinner set for 4 — matte white',
            'no' => 'Keramisk middagssett for 4 — matt hvit',
            'uk' => 'Керамічний набір на 4 особи — матовий білий',
            'ru' => 'Керамический набор на 4 персоны — матовый белый',
        ],
        'desc' => [
            'en' => '16-piece set, dishwasher safe, stackable. Kitchen & homeware catalog demo.',
            'no' => '16-dels sett, oppvaskmaskinsikkert, stabelbart. Demo for kjøkken og interiør.',
            'uk' => '16 предметів, можна в посудомийці, штабельований. Демо для кухні.',
            'ru' => '16 предметов, можно в посудомойке, штабелируемый. Демо для кухни.',
        ],
        'image' => 'https://images.unsplash.com/photo-1578507061120-0e7b9f3a5a0e?w=800&q=80',
    ],
    [
        'id' => 'trail-running-shoes',
        'category' => 'sports-hobbies',
        'featured' => true,
        'active' => true,
        'price' => 1790,
        'sale_price' => 0,
        'sku' => 'SH-SPORT-001',
        'stock' => 28,
        'name' => [
            'en' => 'Trail running shoes — waterproof Nordic edition',
            'no' => 'Terrengløpesko — vanntett nordisk utgave',
            'uk' => 'Кросівки для трейлрану — водонепроникна nordic edition',
            'ru' => 'Кроссовки для трейлрана — водонепроницаемая nordic edition',
        ],
        'desc' => [
            'en' => 'Gore-Tex membrane, Vibram sole, sizes 36–47. Sports store demo with NOK pricing.',
            'no' => 'Gore-Tex-membran, Vibram-såle, størrelser 36–47. Sportbutikk-demo i NOK.',
            'uk' => 'Мембрана Gore-Tex, підошва Vibram, розміри 36–47. Демо спортмагазину.',
            'ru' => 'Мембрана Gore-Tex, подошва Vibram, размеры 36–47. Демо спортмагазина.',
        ],
        'image' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
    ],
    [
        'id' => 'yoga-mat-premium',
        'category' => 'sports-hobbies',
        'featured' => false,
        'active' => true,
        'price' => 690,
        'sale_price' => 549,
        'sku' => 'SH-SPORT-002',
        'stock' => 55,
        'name' => [
            'en' => 'Premium yoga mat — 6 mm natural rubber',
            'no' => 'Premium yogamatte — 6 mm naturgummi',
            'uk' => 'Преміум килимок для йоги — 6 мм натуральний каучук',
            'ru' => 'Премиум коврик для йоги — 6 мм натуральный каучук',
        ],
        'desc' => [
            'en' => 'Non-slip surface, carrying strap included. Fitness & wellness shop demo.',
            'no' => 'Sklisikker overflate, bærestropp inkludert. Demo for treningsbutikk.',
            'uk' => 'Нескользка поверхня, ремінь у комплекті. Демо для фітнес-магазину.',
            'ru' => 'Нескользкая поверхность, ремень в комплекте. Демо для фитнес-магазина.',
        ],
        'image' => 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&q=80',
    ],
    [
        'id' => 'organic-face-serum',
        'category' => 'beauty-health',
        'featured' => true,
        'active' => true,
        'price' => 590,
        'sale_price' => 0,
        'sku' => 'SH-BEAU-001',
        'stock' => 60,
        'name' => [
            'en' => 'Organic hyaluronic face serum — 30 ml',
            'no' => 'Organisk hyaluronsyre ansiktsserum — 30 ml',
            'uk' => 'Органічна сироватка з гіалуроновою кислотою — 30 мл',
            'ru' => 'Органическая сыворотка с гиалуроновой кислотой — 30 мл',
        ],
        'desc' => [
            'en' => 'Vegan, fragrance-free, made in Norway. Beauty & cosmetics storefront demo.',
            'no' => 'Vegansk, parfymefri, laget i Norge. Demo for skjønnhetsbutikk.',
            'uk' => 'Веганська, без ароматизаторів, вироблено в Норвегії. Демо косметики.',
            'ru' => 'Веганская, без отдушек, произведено в Норвегии. Демо косметики.',
        ],
        'image' => 'https://images.unsplash.com/photo-1620916566395-0446834003bf?w=800&q=80',
    ],
    [
        'id' => 'nordic-spa-gift-set',
        'category' => 'beauty-health',
        'featured' => false,
        'active' => true,
        'price' => 1190,
        'sale_price' => 899,
        'sku' => 'SH-BEAU-002',
        'stock' => 20,
        'name' => [
            'en' => 'Nordic spa gift set — body oil & bath salts',
            'no' => 'Nordisk spa-gavesett — kroppolje og badesalt',
            'uk' => 'Подарунковий nordic spa набір — олія та сіль для ванни',
            'ru' => 'Подарочный nordic spa набор — масло и соль для ванны',
        ],
        'desc' => [
            'en' => 'Recyclable packaging, juniper & birch scent. Gift shop and beauty demo.',
            'no' => 'Resirkulerbar emballasje, duft av einer og bjørk. Gave- og skjønnhetsdemo.',
            'uk' => 'Перероблюване пакування, аромат ялівця та берези. Демо подарунків.',
            'ru' => 'Перерабатываемая упаковка, аромат можжевельника и берёзы. Демо подарков.',
        ],
        'image' => 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&q=80',
    ],
    [
        'id' => 'artisan-norwegian-cheese',
        'category' => 'alcohol-food',
        'featured' => true,
        'active' => true,
        'price' => 349,
        'sale_price' => 0,
        'sku' => 'SH-FOOD-001',
        'stock' => 45,
        'name' => [
            'en' => 'Artisan Norwegian brown cheese — 500 g',
            'no' => 'Håndverks brunost — 500 g',
            'uk' => 'Ремісничий норвезький brunost — 500 г',
            'ru' => 'Ремесленный норвежский brunost — 500 г',
        ],
        'desc' => [
            'en' => 'Traditional goat milk brunost from Valdres. Gourmet food shop demo — chilled shipping note.',
            'no' => 'Tradisjonell geitemelk brunost fra Valdres. Matbutikk-demo — kjølefrakt.',
            'uk' => 'Традиційний brunost із коз\'ячого молока. Демо гастрономії — охолоджена доставка.',
            'ru' => 'Традиционный brunost из козьего молока. Демо гастрономии — охлаждённая доставка.',
        ],
        'image' => 'https://images.unsplash.com/photo-1452195100526-56d988da90ae?w=800&q=80',
    ],
    [
        'id' => 'nordic-berry-jam',
        'category' => 'alcohol-food',
        'featured' => false,
        'active' => true,
        'price' => 129,
        'sale_price' => 99,
        'sku' => 'SH-FOOD-002',
        'stock' => 120,
        'name' => [
            'en' => 'Wild Nordic berry jam — cloudberry & lingonberry',
            'no' => 'Vill nordisk bærsyltetøy — multe og tyttebær',
            'uk' => 'Дике nordic варення — морошка та брусниця',
            'ru' => 'Дикое nordic варенье — морошка и брусника',
        ],
        'desc' => [
            'en' => 'Low sugar, glass jar 280 g. Specialty food & grocery catalog demo.',
            'no' => 'Lavt sukkerinnhold, glass 280 g. Demo for spesialmat og dagligvare.',
            'uk' => 'Мало цукру, скляна банка 280 г. Демо для спеціалізованих продуктів.',
            'ru' => 'Мало сахара, стеклянная банка 280 г. Демо для специализированных продуктов.',
        ],
        'image' => 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80',
    ],
    [
        'id' => 'shop-cms-api-monthly',
        'category' => 'php-scripts',
        'featured' => true,
        'active' => true,
        'price' => 49,
        'sale_price' => 0,
        'sku' => 'SH-LIC-API-M',
        'stock' => 999,
        'name' => [
            'en' => 'Shop CMS API — monthly (demo, not real)',
            'no' => 'Shop CMS API — månedlig (demo, ikke ekte)',
            'uk' => 'Shop CMS API — щомісячно (демо, не реальна покупка)',
            'ru' => 'Shop CMS API — ежемесячно (демо, не реальная покупка)',
            'sv' => 'Shop CMS API — månadsvis (demo, inte riktig)',
        ],
        'desc' => [
            'en' => 'Test listing: 49 kr/month for REST API access. Demo only — no real subscription. API keys billed separately.',
            'no' => 'Testoppføring: 49 kr/mnd for API-tilgang. Kun demo — ingen ekte abonnement. API-nøkler faktureres separat.',
            'uk' => 'Тестовий товар: 49 кр/місяць за доступ до API. Лише демо — не справжня підписка. Ключі API окремо.',
            'ru' => 'Тестовый товар: 49 кр/месяц за доступ к API. Только демо — не реальная подписка. Ключи API отдельно.',
            'sv' => 'Testannons: 49 kr/månad för REST API-åtkomst. Endast demo — inget riktigt abonnemang. API-nycklar faktureras separat.',
        ],
        'image' => 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80',
        'seo' => [
            'meta_title' => [
                'en' => 'Shop CMS API monthly — demo 49 kr',
                'no' => 'Shop CMS API månedlig — demo 49 kr',
                'uk' => 'Shop CMS API щомісячно — демо 49 кр',
                'ru' => 'Shop CMS API ежемесячно — демо 49 кр',
                'sv' => 'Shop CMS API månadsvis — demo 49 kr',
            ],
            'meta_description' => [
                'en' => 'Demo subscription for Shop CMS API access at 49 kr/month. Not a real charge — showcase for software licensing in the storefront.',
                'no' => 'Demo-abonnement for Shop CMS API-tilgang til 49 kr/mnd. Ikke ekte betaling — viser programvarelisensiering i butikken.',
                'uk' => 'Демо-підписка на API Shop CMS за 49 кр/місяць. Не справжня оплата — зразок ліцензування в магазині.',
                'ru' => 'Демо-подписка на API Shop CMS за 49 кр/месяц. Не реальная оплата — пример лицензирования в магазине.',
                'sv' => 'Demo-prenumeration för Shop CMS API-åtkomst till 49 kr/månad. Ingen riktig debitering — visar programvarulicensiering i butiken.',
            ],
        ],
    ],
    [
        'id' => 'shop-cms-updates-yearly',
        'category' => 'php-scripts',
        'featured' => true,
        'active' => true,
        'price' => 349,
        'sale_price' => 249,
        'sku' => 'SH-LIC-UPD-Y',
        'stock' => 999,
        'name' => [
            'en' => 'Shop CMS updates — 1 year (demo, not real)',
            'no' => 'Shop CMS oppdateringer — 1 år (demo, ikke ekte)',
            'uk' => 'Shop CMS оновлення — 1 рік (демо, не реальна покупка)',
            'ru' => 'Shop CMS обновления — 1 год (демо, не реальная покупка)',
            'sv' => 'Shop CMS uppdateringar — 1 år (demo, inte riktig)',
        ],
        'desc' => [
            'en' => 'Test listing: 249 kr for all version updates for 12 months. Demo only — includes security patches and minor releases.',
            'no' => 'Testoppføring: 249 kr for alle oppdateringer i 12 måneder. Kun demo — sikkerhetsoppdateringer og mindre releaser.',
            'uk' => 'Тестовий товар: 249 кр за всі оновлення протягом року. Лише демо — патчі безпеки та мінорні релізи.',
            'ru' => 'Тестовый товар: 249 кр за все обновления в течение года. Только демо — патчи безопасности и минорные релизы.',
            'sv' => 'Testannons: 249 kr för alla versionsuppdateringar i 12 månader. Endast demo — inkluderar säkerhetspatchar och mindre releaser.',
        ],
        'image' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
        'seo' => [
            'meta_title' => [
                'en' => 'Shop CMS yearly updates — demo 249 kr',
                'no' => 'Shop CMS årlige oppdateringer — demo 249 kr',
                'uk' => 'Shop CMS оновлення на рік — демо 249 кр',
                'ru' => 'Shop CMS обновления на год — демо 249 кр',
                'sv' => 'Shop CMS årliga uppdateringar — demo 249 kr',
            ],
            'meta_description' => [
                'en' => 'Demo annual update plan for Shop CMS at 249 kr/year. Not a real purchase — showcases software maintenance pricing.',
                'no' => 'Demo årsplan for Shop CMS-oppdateringer til 249 kr/år. Ikke ekte kjøp — viser prising for programvarevedlikehold.',
                'uk' => 'Демо-тариф оновлень Shop CMS на рік за 249 кр. Не справжня покупка — зразок ціни на підтримку ПЗ.',
                'ru' => 'Демо-тариф обновлений Shop CMS на год за 249 кр. Не реальная покупка — пример цены на поддержку ПО.',
                'sv' => 'Demo årsplan för Shop CMS-uppdateringar till 249 kr/år. Inget riktigt köp — visar prissättning för programvaruunderhåll.',
            ],
        ],
    ],
];

$ecoFile = dirname(__DIR__) . '/data/products-ecosystem-cms.php';
if (!is_readable($ecoFile)) {
    $ecoFile = dirname(__DIR__, 2) . '/data/products-ecosystem-cms.php';
}
if (is_readable($ecoFile)) {
    $eco = require $ecoFile;
    if (is_array($eco)) {
        $products = array_merge($products, $eco);
    }
}

return $products;